maintainer        "Crowd Interactive"
maintainer_email  "adrian.castillo@crowdint.com"
license           "MIT"
description       "Configure frequently-used tools for an OSX workstation"
long_description  "Configure frequently-used tools for an OSX workstation"
version           "1.0.0"
supports          "mac_os_x"
depends           "dmg"
